### ISSUE TITLE
Installation failed on Windows 10 with '.' is not recognized as an internal or external command error. 

### ISSUE THREAD

**Issue by gswftw** [cryptocoinjs/secp256k1-node#113]
I've seen other issues regarding this, but eccrypto uses secp256k1@2.0.10 as a dependency.  The following errors still occur on npm install.  I already tried [this](https://github.com/cryptocoinjs/secp256k1-node/tree/15e14632eabfa54248af97f3ff7a9dcf96f67271#windows)...

```
'.' is not recognized as an internal or external command, operable program or batch file.
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\lmn\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lmn\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lmn\Documents\test\node_modules\secp256k1
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@2.0.10 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.10 rebuild script.
```

**Comment by fanatid** [comment]
all should works even if build fail, IIRC for v2

**Comment by gswftw** [comment]
Not for eccrypto: "WebCryptoAPI is not available" error thrown from browser.js, which is the fallback implementation when failed to use secp256k1 node...

**Comment by fanatid** [comment]
you're not right, in browser eccrypto do not uses secp256k1

**Comment by gswftw** [comment]
That error was thrown.

**Comment by imeckler** [comment]
Any updates on this?

**Comment by dcousens** [comment]
Anyone able to reproduce?

**Comment by Mayhem93** [comment]
@dcousens I am, but I don't have openssl installed in the location where **bindings.gyp** says (I installed it with vcpkg) so I removed those lines in the file and tried installing it.

**Comment by grinchukav** [comment]
Still have the same problem. Solution not found yet.

**Comment by sidhujag** [comment]
Can you use 3.5.0? It should work. Update the package.json of eccrypto to 3.5 do an install and I lock my package with 3.5 so other developers may pull eccrypto as is but still work cause of package lock.

**Comment by Mayhem93** [comment]
```
> npm run rebuild || echo "Secp256k1 bindings compilation fail. Pure JS implementation will be used."


> secp256k1@3.5.0 rebuild D:\workspace\secp256k1-node
> node-gyp rebuild


D:\workspace\secp256k1-node>if not defined npm_config_node_gyp (node "C:\Users\uther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\uther\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
D:\workspace\secp256k1-node\build\..\src\secp256k1-src\src\secp256k1.c
D:\workspace\secp256k1-node\build\..\src\secp256k1-src\contrib\lax_der_parsing.c
D:\workspace\secp256k1-node\build\..\src\secp256k1-src\contrib\lax_der_privatekey_parsing.c
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  addon.cc
  privatekey.cc
  publickey.cc
  signature.cc
  ecdsa.cc
  ecdh.cc
  win_delay_load_hook.cc
..\src\privatekey.cc(3): fatal error C1083: Cannot open include file: 'secp256k1.h': No such file or directory [D:\workspace\secp256k1-node\build\secp256k1.vcxproj]
..\src\publickey.cc(4): fatal error C1083: Cannot open include file: 'secp256k1.h': No such file or directory [D:\workspace\secp256k1-node\build\secp256k1.vcxproj]
..\src\signature.cc(3): fatal error C1083: Cannot open include file: 'secp256k1.h': No such file or directory [D:\workspace\secp256k1-node\build\secp256k1.vcxproj]
..\src\addon.cc(3): fatal error C1083: Cannot open include file: 'secp256k1.h': No such file or directory [D:\workspace\secp256k1-node\build\secp256k1.vcxproj]
..\src\ecdsa.cc(3): fatal error C1083: Cannot open include file: 'secp256k1.h': No such file or directory [D:\workspace\secp256k1-node\build\secp256k1.vcxproj]
..\src\ecdh.cc(3): fatal error C1083: Cannot open include file: 'secp256k1.h': No such file or directory [D:\workspace\secp256k1-node\build\secp256k1.vcxproj]
```

:( (on the master branch ofc)

**Comment by shahnawaz** [comment]
I was also facing the same issue 

```
'.' is not recognized as an internal or external command,
operable program or batch file.
gyp: Call to './utils/has_lib.sh gmpxx && ./utils/has_lib.sh gmp' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Shahnawaz Ali\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:305:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:225:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Shahnawaz Ali\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"

gyp ERR! cwd D:\project_path\node_modules\secp256k1
gyp ERR! node -v v10.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

Environment (Previously):
OS: Windows 10
node: v10.0.0
npm: 4.1.1
node-gyp: v3.6.2
python: 2.7.14
windows build tools: 2015

After reading some issues here and there I tried

**npm install npm@next -g**

This created some different issues for me (but that '.' issue was solved though)

Then I realized that some dependencies are not yet supported by/supporting node v10.0.0 so I shifted to v8.11.1 (the recommended version of node.js) and it solved my problems.

Environment (Now):
OS: Windows 10
node: **v8.11.1**
npm: 6.0.0
node-gyp: v3.6.2
python: 2.7.14
windows build tools: 2015

**Comment by aleybovich** [comment]
Has this been looked at? Two years later, still the same issue on Windows..

**Comment by deepakvparmar** [comment]
Any solution for this issue? I am also facing same issue, but not able to find right solution.

**Comment by CriptoGirl** [comment]
I am getting the following error:
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\...\....\....\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax

**Comment by H3ll3m4** [comment]
> I am getting the following error:
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: C:\Users...........\Programs\Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack File "", line 1
> gyp ERR! stack import sys; print "%s.%s.%s" % sys.version_info[:3];
> gyp ERR! stack ^
> gyp ERR! stack SyntaxError: invalid syntax

I have the same error. I'm using windows, running npm from the terminal and powershell and I have python 3 installed.

**Comment by junderw** [comment]
node-gyp only supports python 2 iirc.

**Comment by maroodb** [comment]
any solution to this problem ?

**Comment by LuizHenriqueCezar** [comment]
Any resolution found around this issue? I am also facing same issue.

**Comment by fanatid** [comment]
If somebody still have issues with Windows, please try version 4.0.0
https://github.com/cryptocoinjs/secp256k1-node/pull/160
